###------------------------------------------------------------------------------------------------
# script:  details.inc
# purpose: Application specific details to assist in the generation of README.md
# version: 1.0.0
###------------------------------------------------------------------------------------------------

DETAILS_NAME="CID"
DETAILS_NAME_ABBR="cid"
DETAILS_DESCRIPTION=(
    'Extends the capabilities of the CI Toolsets such as Jenkins and Azure DevOps'
)
DETAILS_PREREQUISITES=(
    'Linux'
    'BASH shell'
)
DETAILS_DEPENDENCIES=(
    'none, apart from the standard binaries installed as part of a modern Linux Distro (tested on RHEL and Debian variants, other distros mileage may vary)'
    'additional dependencies are required for specific Toolsets, please see the Required Executeables detail as indicated in the Library Function files'
)
